# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(default=0)),
                ('breed', models.CharField(max_length=128)),
                ('image', models.ImageField(max_length=255, upload_to='pictures/%Y/%m%d/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
