# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_leash', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
