# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden_leash', '0003_userprofile_isowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isOwner',
            new_name='is_owner',
        ),
    ]
