# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden_leash', '0006_userprofile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
